variables:
  SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar' 
  GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'dev'


sonarcloud-check:
  stage: sonarcloud-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - |
      npm i -g corepack
      corepack enable
      yarn install
      yarn lint && yarn test -- --coverage --testResultsProcessor=jest-sonar-reporter
      yarn build
      sonar-scanner
  only:
    - merge_requests
    - main
  interruptible: true

".inject":
  stage: inject
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - echo "$S3_ENV"
    - aws s3 cp "$S3_ENV" .env
  artifacts:
    paths:
      - .env

inject_prod:
  environment: 
    name: production
  extends: ".inject"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      
inject_review:
    environment:
      name: review/$CI_COMMIT_REF_NAME
    extends: ".inject"
    rules:
      - if: '$CI_COMMIT_REF_PROTECTED == "true"'


include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml

stages:
- ".pre"
- sonarcloud-check
- inject
- build
- test
- review
- deploy
- production
- cleanup
- ".post"